apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slack.secretName }}
  labels:
    {{- include "halbert.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.slack.token | b64enc | quote }}