apiVersion: v2
name: k3s-cluster-docs
description: Private internal handbook for a K3s cluster
type: application
version: 1.0.10
appVersion: "1.0.10"
kubeVersion: ">=1.25.0-0"
home: https://github.com/jonfairbanks/k3s-cluster-docs
sources:
  - https://github.com/jonfairbanks/k3s-cluster-docs
maintainers:
  - name: Jon Fairbanks
    url: https://github.com/jonfairbanks
