replicaCount: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: ""

image:
  repository: ghcr.io/jonfairbanks/k3s-cluster-docs
  tag: "1.0.10"
  digest: "sha256:2421001a7f7c73ac1320d4e38625166ad18a784fcc978093d5252c1e78903649"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: cluster-docs.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
