apiVersion: v2
name: rick
description: A self-hosted, self-contained Rickroll
type: application
version: 2.0.1
appVersion: "1080p"
kubeVersion: ">=1.25.0-0"
home: https://github.com/jonfairbanks/helm-charts
sources:
  - https://github.com/jonfairbanks/helm-charts
  - https://github.com/modem7/docker-rickroll
maintainers:
  - name: Jon Fairbanks
    url: https://github.com/jonfairbanks
