replicaCount: 1

image:
  repository: modem7/docker-rickroll
  tag: "1080p"
  digest: "sha256:4214f8999939462cd6619779526fd1c79870613edaa966b8b707f4d61d6281a8"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

containerPorts:
  http: 8080
  health: 9090

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: rick.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 25m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 75

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

nodeSelector: {}
tolerations: []
affinity: {}
