affinity: {}

apiURL: "https://api.host.tld/api/"
auth: "false"
auth0Client: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
auth0Domain: yourdomain.auth0.com
baseURL: "http://host.tld"
namePlaceholder: Rick
socketURL: "https://host.tld"
urlPlaceholder: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
apiServiceName: yo-api
apiServicePort: 80

fullnameOverride: ""
image:
  pullPolicy: Always
  repository: jonfairbanks/yo-client
imagePullSecrets: []
ingress:
  annotations: 
    nginx.ingress.kubernetes.io/server-snippet: |-
      location ~* "^/[0-9a-z!?@_-]{1,99}$"  {
        proxy_set_header X-Real-IP $remote_addr;
        rewrite ^/(.*)$ http://$host/api/link/$1 redirect;
      }
  enabled: true
  hosts:
  - host: fbnks.io
    paths:
    - /
  tls: []
nameOverride: ""

nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  create: true
  name: null

tolerations: []

