{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "rick.labels" . | nindent 4 }}
  name: {{ include "rick.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "rick.selectorLabels" . | nindent 6 }}
  {{- if ne (toString .Values.podDisruptionBudget.minAvailable) "" }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
